name: Lint, Build and Deploy to Firebase on merge

on:
  push:
    branches:
      - master
      - 'release/**'

jobs:
  lint_build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run linting
        run: npm ci && npm run lint
        continue-on-error: false

      - name: Build and Test
        if: success() && github.event_name == 'pull_request'
        run: npm run build

      - name: Deploy to Firebase
        if: success() && github.event_name == 'pull_request'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SUMMARIZE_NG }}'
          channelId: live
          projectId: summarize-ng
